### ISSUE TITLE
API broken by upgrade from 0.0.1 to 0.1

### ISSUE THREAD

**Issue by rbu** [sublee/caselib#1]
The main caselib API function was apparantly changed in the upgrade from 0.0.1 to 0.1. This was not reflected anywhere in release notes or similar on either PyPI, the project homepage or a RELEASE_NOTES file.

To make the code backwards-compatible, it should be possible to check whether "text" parameter is of type "Case" and fall back to original behavior.

**Comment by sublee** [comment]
I'm so sorry. It's my fault. The version 0.1.0 was too hastiness. I accepted your suggestion and uploaded new version. Please upgrade the module on your system.

Thanks.

**Comment by rbu** [comment]
Awesome, thank you!
